[tool.isort]
force_single_line = true
import_heading_firstparty = "betanin"
import_heading_stdlib = "standard library"
import_heading_thirdparty = "3rd party"
known_first_party = "betanin"
length_sort = true
lines_after_imports = 2
multi_line_output = 3
sections = "STDLIB,THIRDPARTY,FIRSTPARTY"

[tool.black]
line-length = 79
target_version = ['py39']

[tool.pylint.'messages control']
# `no-member` because: https://github.com/PyCQA/pylint/issues/2917
# `*-docstring` because lazy (at the moment)
# `unused-import` because the isort/autoflake is doing this already the exception comment differs
# `wrong-import-position` for the same reason
enable = "all"
disable = """\
	missing-module-docstring,\
	missing-class-docstring,\
	missing-function-docstring,\
	no-member,\
	fixme,\
	too-few-public-methods,\
	unused-import,\
	wrong-import-position\
"""

[tool.pyright]
include = ["betanin"]
venv = "betanin"
pythonVersion = "3.9"
pythonPlatform = "Linux"
